version: '3'
services:
  app:
    image: pratamarizki22/todolist-app:latest
    container_name: todolist-app
    ports:
      - "3000:3000"
      - "5000:5000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    command: npm start
