version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pratamarizki22/todolist-app:latest
    ports:
      - "3000:3000"
      - "5000:5000"
    environment:
      - NODE_ENV=production
