apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlite
  template:
    metadata:
      labels:
        app: sqlite
    spec:
      containers:
      - name: sqlite
        image: sqlite:latest
        ports:
        - containerPort: 3306
        resources:
          requests:
            memory: "16Mi"
            cpu: "50m"
          limits:
            memory: "32Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: sqlite
spec:
  selector:
    app: sqlite
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: LoadBalancer
